### ISSUE TITLE
Gradle을 통한 빌드 자동화

### ISSUE THREAD

**Issue by YoungJun-L** [SE-Team-19/tetris#12]
나중에 github actions으로 테스트 자동화할 때도 유용할 것 같습니다
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

**Comment by bangga0403** [comment]
Gradle build 시 글자 깨짐 현상이 발생할 경우에는 build.gradle에 다음 구문을 추가해주시면 됩니다.

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

http://ojc.asia/bbs/board.php?bo_table=LecSpring&wr_id=489

**Comment by bangga0403** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [22-03-25 Fri](https://trello.com/c/ccafTzNm/23-22-03-25-fri)

**Comment by YoungJun-L** [comment]
#17

**Comment by YoungJun-L** [comment]
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [22-03-25 Fri](https://trello.com/c/ccafTzNm/23-22-03-25-fri)
