### ISSUE TITLE
Sharing view instances in MVC pattern

### ISSUE THREAD

**Issue by YoungJun-L** [SE-Team-19/tetris#14]
controller에서 view instance를 공유할 때 어떻게 하는 것이 좋을까요

저는 view를 싱글톤 패턴으로 작성하면 될 것 같습니다.
```java
public class View {
    private static final View view = new View();
    private View() {}

    public static View getInstance() {
        return view;
    }
}
```

**Comment by bangga0403** [comment]
View 객체들이 Singleton pattern 을 따르도록 수정했습니다. 3685d0010855756cf7ac3aa30ae19d65017412cd
좋은 정보 감사드립니다.

**Comment by bangga0403** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [22-03-30 Wed](https://trello.com/c/PInthT1X/35-22-03-30-wed)

**Comment by Moojun** [comment]
저도 Singleton pattern 사용에 동의합니다.

**Comment by YoungJun-L** [comment]
#17
