### ISSUE TITLE
Create MainView

### ISSUE THREAD

**Issue by Moojun** [SE-Team-19/Tetris#6]
## 개발사항
* MainView.java
  * 테트리스 게임 시작 화면 구현을 위해 작성
* ScoreView.java, GameView.java, SettingView.java, ExitView.java
  * MainView.java 구성을 위해 선언

#5

**Comment by bangga0403** [comment]
Model의 Block.java랑 Player.java도 변경 하신 건가요?

**Comment by Moojun** [comment]
package 부분 import 하는 과정에서 변경 사항이 있었네요. 이거는 금요일 미팅 때 다시 확인해보면 좋을 것 같아요

**Comment by bangga0403** [comment]
> package 부분 import 하는 과정에서 변경 사항이 있었네요. 이거는 금요일 미팅 때 다시 확인해보면 좋을 것 같아요

네 알겠습니다!
