### ISSUE TITLE
About Refactoring MainView and ViewController

### ISSUE THREAD

**Issue by bangga0403** [SE-Team-19/tetris#8]
#7 
JFrame 생성을 MainView가 아닌 ViewController가 수행하도록 하였습니다. 그에 따른 변경 사항들입니다.

### 변경사항
1. 모든 View는 JPanel을 상속받는다.
2. ViewController에서 JFrame을 수행하고 각 View는 getContentPane()을 통해 View panel들을 실장한다.
3. ViewController에서 MainView의 JButton에 EventListener을 직접 삽입한다.
 * 때문에 MainView의 JButton들의 접근지정자가 public으로 바뀌었다.
4. ViewController에서 직접 View들의 크기를 조정할 수 있게 되었다.

### 기대효과
* View는 swing의 컴포넌트를 생성만 하고 모든 것을 ViewController가 통제하기 때문에 MVC 패턴에 좀 더 가까워지리라 예상

### 문제점
* JButton의 접근지정자가 public으로 변경되어 OOP 원칙에 위배된다.
*  ViewController 인스턴스가 무거워진다.

이에 따른 팀원들의 의견이 궁금합니다.

**Comment by Moojun** [comment]
제 생각은, 문제점에 적힌 것처럼 ViewController가 View의 기능 대다수를 포함하게 되어 상당히 클래스 자체가 무거워질 것으로 예상됩니다. 따라서, View의 크기 설정 등처럼 View의 구현에 관련된 부분은 ViewController가 아닌 View에 넣어도 될 것 같아요. 이거는 내일 회의 시간에 다시 한 번 의논하면 좋을 것 같아요

**Comment by YoungJun-L** [comment]
> 제 생각은, 문제점에 적힌 것처럼 ViewController가 View의 기능 대다수를 포함하게 되어 상당히 클래스 자체가 무거워질 것으로 예상됩니다. 따라서, View의 크기 설정 등처럼 View의 구현에 관련된 부분은 ViewController가 아닌 View에 넣어도 될 것 같아요. 이거는 내일 회의 시간에 다시 한 번 의논하면 좋을 것 같아요

저도 이거 동의하고 버튼 이벤트리스너들도 view에 포함하는 게 나을 듯 하네요
